title: Title
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#4205b3"
  secondary-color: "#f51515"
  media-colors:
    - title: media-color-one
      color: "#7272f8"
    - title: media-color-two
      color: "#54a4f5"
    - title: media-color-three
      color: "#54a4f5"
    - title: media-color-four
      color: "#4da7ff"
    - title: media-color-five
      color: "#6b87ff"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moe-andersonpri-staging.netlify.app
prod: https://moe-andersonpri-prod.netlify.app
resources_name: announcements
